### PR TITLE
Unbreak build with Boost 1.69

### PR DESCRIPTION
**Pull request by jbeich**
After boostorg/serialization@af46ac2da3e9 (post-Beta1) build fails. See [error log](https://ptpb.pw/8Rh1).

```c++
src/systems/base/gan_graphics_object_data.cc:56:12: error: no member named 'cerr' in namespace 'std'
using std::cerr;
      ~~~~~^
```

### CODE REVIEW

**Comment by eglaysher** [comment]
Thank you!
